apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testapi
  namespace: flux-testapi
spec:
  releaseName: testapi
  chart:
    spec:
      chart: testapi
      sourceRef:
        kind: HelmRepository
        name: paolosalvatori
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: paolosalvatori/testapi
      pullPolicy: IfNotPresent
      tag: "v1"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/acme-challenge-type: http01
        cert-manager.io/cluster-issuer: letsencrypt-nginx
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: testapi.babosbird.com
      tls:
      - hosts:
        - testapi.babosbird.com