apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testapi
  namespace: flux-testapi
spec:
  chart:
    spec:
      version: ">=0.1.0"
  values:
    ingress:
      hosts:
      - host: miatestapi.babosbird.com
      tls:
      - hosts:
        - miatestapi.babosbird.com